/**:
    ros__parameters:
        use_sim_time: False
        rate: 5.0
        min_cost: 1 # Minimum cost in the range of [0, 100]
        max_cost: 100 # Maximum (unsafe) cost in the range of [0, 100]
        decay_rate: 0.1 # Decay rate for repulsive cost
        occupancy_threshold: 0.5
