/**:
    ros__parameters:
        use_sim_time: False
        rate: 1
        min_cost: 1 # Minimum cost in the range of [0, 100]
        max_cost: 100 # Maximum (unsafe) cost in the range of [0, 100]
        decay_rate: 1.0 # Decay rate for repulsive cost
        #clearance: 0.2
